"""Small helper module for Exercise 21. Do NOT edit this file."""


def add(a, b):
    return a + b


def subtract(a, b):
    return a - b


def divide(a, b):
    return a / b


def is_even(n):
    return n % 2 == 0
